routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
 Route::get('/', 'HomeController@index')->name('welcome');
 Route::Post('/reservation', 'ReservationController@reserv')->name('reservation.reserv');
 Route::Post('/contact', 'ContactController@message')->name('contact.message');

Auth::routes();

//Route de l'administrateur
Route::group(['prefix'=>'admin', 'middleware'=>'auth', 'namespace'=>'admin'], function (){
 //    route du dashboard
    Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');
//    route des slides
    Route::resource('slider', 'SliderController');
//    route des categories
    Route::resource('category', 'CategoryController');
//    route des articles
    Route::resource('article', 'ArticleController');
 //    route des réservations
    Route::get('reservation', 'ReservationController@index')->name('reservation.index');
    
    Route::post('reservation/{id}', 'ReservationController@statut')->name('reservation.statut');

    
    Route::delete('reservation/{id}', 'ReservationController@destroy')->name('reservation.destroy');
    
    Route::get('contact', 'ContactController@index')->name('contact.index');
    
    Route::get('contact/{id}', 'ContactController@show')->name('contact.show');
    
     Route::delete('contact/{id}', 'ContactController@destroy')->name('contact.destroy');

   
});

app/Articles.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;

class Articles extends Model
{

 protected $table = 'articles';
 
     protected $fillable = [
         'name', 'description', 'price', 'image', 'category_id',
    ];
     
//     relation avec categorie
    public function category() {
     
//     appel du model des articles
      return $this->belongsTo(Category::class);
     
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Articles;
use App\Category;
use Carbon\Carbon;
use App\Http\Controllers\Controller;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Articles::all();
	  return view('admin.article.index', compact('articles'));  
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         
	  
	  $categories = Category::all();
        return view('admin.article.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         request()->validate([
	     'category' => 'required', 
	     'name' => 'required|string', 
	     'description' => 'string', 
	     'price' => 'required|integer', 
	     'image' => 'mimes:jpeg,jpg,bmp,png', 
	 ]);
	   
	 $image = $request->file('image');
	 $slug = str_slug($request->name);
	 if (isset($image)){
	    $currenDate = Carbon::now()->toDateString();
	    $imagename = $slug .'-'. $currenDate .'-'. uniqid() .'.'. $image->getClientOriginalExtension();
	    if (!file_exists('uploads/article')){
	     mkdir('uploads/article', 0777, true);
	    }
	    $image->move('uploads/article', $imagename);
	 }
	else {
        $imagename = 'default.png';
      }
	
	$article = new Articles();
	$article->category_id = $request->category;
	$article->name = $request->name;
	$article->description = $request->description;
	$article->price = $request->price;
	$article->image = $imagename;
      $article->save();
	
	
	return redirect()->route('article.index')->with('success', 'Article ajouté avec succès !');
    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Articles::find($id);
	  return view('admin.article.edit', compact('article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       request()->validate([
	    'category' => 'required', 
	     'name' => 'string', 
	     'description' => 'string', 
	     'price' => 'integer', 
	     'image' => 'mimes:jpeg,jpg,bmp,png', 
	 ]);
	 $image = $request->file('image');
	 $slug = str_slug($request->name);
	 $article = Articles::find($id);
	 if (isset($image)){
	    $currenDate = Carbon::now()->toDateString();
	    $imagename = $slug .'-'. $currenDate .'-'. uniqid() .'.'. $image->getClientOriginalExtension();
	    if (!file_exists('uploads/article')){
	     mkdir('uploads/article', 0777, true);
	    }
	    $image->move('uploads/article', $imagename);
	 }
	else {
        $imagename = $article->image;
      }
	
             $article->name = $request->name;
             $article->description = $request->description;
             $article->price = $request->price;
             $article->image = $imagename;  
             $article->save();
	return redirect()->route('article.index')->with('success', 'Article modifié avec succès !');
    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         $article = Articles::find($id);
	 if (file_exists('uploads/article/'.$article->image))
	 {
	    unlink('uploads/article/'.$article->image);
	   
	 }
	  $article->delete();  
	  return redirect()->back()->with('success', 'Article supprimé avec succès !');
    }
}

resources/views/admin/article/create.blade.php
@extends('layouts.app')

<!--titre du slider-->
@section('title', 'Article')

@push('css')


@endpush

@section('content')
    <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
		 <!--		Message flash d"erreur de validation-->
		  
		   @if ($errors->any())
                    <div class="alert alert-danger">
			   <ul>
			       @foreach ($errors->all() as $error)
				   <div class="alert alert-danger">
				    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<i class="material-icons">*</i>
				    </button>
				    <span>
					<b> Danger - {{ $error }}</span>
				  </div>
				 @endforeach
			   </ul>
                       
                    </div>
                @endif
		  
<!--	Message flash-->
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Ajouter un article</h4>
                </div>
                <div class="card-body">
                  <div class="card-content">
			 <form method="POST" action="{{ route('article.store')}}" enctype="multipart/form-data">
			      @csrf
				 <div class="row">
					<div class="col-md-12">
					  <div class="form-group">
					    <label class="bmd-label-floating">Choisir une categorie</label>
					    <select  name="category" class="form-control">
					         @foreach ($categories as $key=>$category)
						   <option value="{{ $category->id }}">{{ $category->name }}</option>
						   @endforeach
					     
					    </select>
					  </div>
					</div>
				 </div>
				 <div class="row">
					<div class="col-md-12">
					  <div class="form-group">
					    <label class="bmd-label-floating">Nom</label>
					    <input type="text" name="name" class="form-control">
					  </div>
					</div>
				 </div>
				 <div class="row">
					<div class="col-md-12">
					  <div class="form-group">
					    <label class="bmd-label-floating">Description</label>
					    <textarea name="description" id="" cols="30" rows="10" name="description" class="form-control"></textarea>
					  </div>
					</div>
				 </div>
				 <div class="row">
				     <div class="col-md-12">
					 <div class="form-group">
					   <label class="bmd-label-floating">Prix</label>
					   <input type="number" name="price" class="form-control">
					 </div>
				     </div>
                         </div>
				 <div class="row">
				     <div class="col-md-12">
					   <label class="control-label">Image</label>
					   <input type="file" name="image" class="form-control">
				     </div>
                         </div><br><br>
				  <a href="{{ route('article.index')}}" class="btn btn-danger">Retour</a>
				<button type="submit" class="btn btn-primary">Ajouter</button>
			 </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
       

@endsection


@push('script')

 

@endpush

resources/views/admin/article/edit.blade.php
@extends('layouts.app')

<!--titre du slider-->
@section('title', 'Categorie')

@push('css')


@endpush

@section('content')
    <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
		 <!--		Message flash d"erreur de validation-->
		   @include('layouts.partial.messages')
<!--	Message flash-->
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Editer la categorie</h4>
                </div>
                <div class="card-body">
                  <div class="card-content">
			 <form method="POST" action="{{ route('article.update', $article->id)}}">
			      @csrf
				@method('PUT')
				 <div class="row">
					<div class="col-md-12">
					  <div class="form-group">
					    <label class="bmd-label-floating">Categorie</label>
					    <input type="text" name="name" class="form-control" value="{{ $article->name}}">
					  </div>
					</div>
				 </div>
				 <div class="row">
					<div class="col-md-12">
					  <div class="form-group">
					    <label class="bmd-label-floating">Nom</label>
					    <input type="text" name="name" class="form-control" value="{{ $article->name}}">
					  </div>
					</div>
				 </div>
				 <div class="row">
				     <div class="col-md-12">
					 <div class="form-group">
					   <label class="bmd-label-floating">Description</label>
					   <input type="text" name="slug" class="form-control" value="{{ $article->slug}}">
					 </div>
				     </div>
                         </div><br><br>
				 <a href="{{ route('category.index')}}" class="btn btn-danger">Retour</a>
				<button type="submit" class="btn btn-primary">Editer</button>
			  
			 </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
       

@endsection


@push('script')

 

@endpush

resources/views/admin/article/index.blade.php
@extends('layouts.app')

<!--titre du slider-->
@section('title', 'Slider')

@push('css')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/plug-ins/3cfcc339e89/integration/bootstrap/3/dataTables.bootstrap.css">

@endpush

@section('content')
    <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
<!--		Message flash-->
            @include('layouts.partial.messages')
<!--	end	Message flash-->
<!--		 boutton d'ajout du nouveau slide-->
		  <a href="{{ route('article.create') }}" class="btn btn-info">Ajouter un article</a> 
<!--	end	 boutton d'ajout du nouveau slide-->		  
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Listes des articles</h4>
			
                </div>
                <div class="card-body">
                  <div class="table-responsive">
			 <table id="example" class="table" style="width:900px;">
                      <thead class=" text-primary">
				  <th>ID</th>
				  <th>Nom categorie</th>
				  <th>Nom</th>
				  <th>Destription</th>
				  <th>Prix</th>
				  <th>Image</th>
				  <th>Date de création</th>
				  <th>Date de modification</th>
				  <th>Actions</th>
                      </thead>
                      <tbody>
			       @foreach ($articles as $key=>$article)
				    <tr>
					  <td class="badge">{{ $key +1 }}</td>
					  <td>{{ $article->category->name ?? '' }}</td>
					  <td>{{ $article->name }}</td>
					  <td>{{ $article->description }}</td>
					  <td>{{ $article->price }}</td>
					  <td><img src="{{ asset('uploads/article/'.$article->image )}}" class="img-responsive img-thumbnail" style="height: 100px; width: 100px"></td>
					  <td>{{ $article->image }}</td>
					  <td>{{ $article->created_at }}</td>
					  <td>{{ $article->updated_at }}</td>
					  <td>
					   <a href="{{ route('article.edit', $article->id )}}" class="btn btn-info btn-sm"><i class="material-icons">mode_edit</i></a>
					   <form id="delete-form-{{ $article->id}}" action="{{ route('article.destroy',$article->id) }}" method="POST" style="display: none;">
					     @csrf
					     @method('DELETE')
					   </form>
					   <button type="button" class="btn btn-info btn-sm"  onclick="if(confirm('Voulez-vous vraiment supprimer cette categorie ?')){
						 event.preventDefault();
						 document.getElementById('delete-form-{{ $article->id}}').submit();
						}else{
						 event.preventDefault();
						}" ><i class="material-icons">delete</i></button>
					  </td>
				    </tr>
				  
				  @endforeach 
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
       

@endsection


@push('script')

 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
<script language="JavaScript" src="https://cdn.datatables.net/plug-ins/3cfcc339e89/integration/bootstrap/3/dataTables.bootstrap.js" type="text/javascript"></script>
 <script>
        $(document).ready(function() {
        $('#example').DataTable( {
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/French.json"
            }

        } );
         $("[data-toggle=tooltip]").tooltip();
           } );
</script>

@endpush