routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
 Route::get('/', 'HomeController@index')->name('welcome');
 Route::Post('/reservation', 'ReservationController@reserv')->name('reservation.reserv');
 Route::Post('/contact', 'ContactController@message')->name('contact.message');

Auth::routes();

//Route de l'administrateur
Route::group(['prefix'=>'admin', 'middleware'=>'auth', 'namespace'=>'admin'], function (){
 //    route du dashboard
    Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');
//    route des slides
    Route::resource('slider', 'SliderController');
//    route des categories
    Route::resource('category', 'CategoryController');
//    route des articles
    Route::resource('article', 'ArticleController');
 //    route des réservations
    Route::get('reservation', 'ReservationController@index')->name('reservation.index');
    
    Route::post('reservation/{id}', 'ReservationController@statut')->name('reservation.statut');

    
    Route::delete('reservation/{id}', 'ReservationController@destroy')->name('reservation.destroy');
    
    Route::get('contact', 'ContactController@index')->name('contact.index');
    
    Route::get('contact/{id}', 'ContactController@show')->name('contact.show');
    
     Route::delete('contact/{id}', 'ContactController@destroy')->name('contact.destroy');

   
});

app/Category.php
<?php

namespace App;


use Illuminate\Database\Eloquent\Model;

class Category extends Model
{

    protected $fillable = [
        'name', 'slug',
    ];
    public function articles() 
	   { 
           return $this->hasMany(Articles::class); 
	   
	   }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Category;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $categories= Category::all();
        return view('admin.category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
	     'name' => 'required', 
	 ]);
	  $category = new Category([ 
             'name' => $request->get('name'),
            'slug' => str_slug($request->get('slug')),
	     ]);
     $category->save();
     return redirect()->route('category.index')->with('success', 'Categorie ajoutée avec succès !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $category = Category::find($id);
	  return view('admin.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        request()->validate([
	     'name' => 'required', 
	 ]);
	   $category = Category::find($id);
	   $category->name = $request->name;
	   $category->slug = str_slug($request->slug);
         $category->save();
	return redirect()->route('category.index')->with('success', 'Categorie modifiée avec succès !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
	  $category->delete();  
	  return redirect()->back()->with('success', 'Categorie supprimée avec succès !');
    }
}

resources/views/admin/category/create.blade.php
@extends('layouts.app')

<!--titre du slider-->
@section('title', 'Categorie')

@push('css')


@endpush

@section('content')
    <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
		 <!--		Message flash d"erreur de validation-->
		  
		   @if ($errors->any())
                    <div class="alert alert-danger">
			   <ul>
			       @foreach ($errors->all() as $error)
				   <div class="alert alert-danger">
				    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<i class="material-icons">*</i>
				    </button>
				    <span>
					<b> Danger - {{ $error }}</span>
				  </div>
				 @endforeach
			   </ul>
                       
                    </div>
                @endif
		  
<!--	Message flash-->
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Ajouter une categorie</h4>
                </div>
                <div class="card-body">
                  <div class="card-content">
			 <form method="POST" action="{{ route('category.store')}}" enctype="multipart/form-data">
			      @csrf
				 <div class="row">
					<div class="col-md-12">
					  <div class="form-group">
					    <label class="bmd-label-floating">Nom</label>
					    <input type="text" name="name" class="form-control">
					  </div>
					</div>
				 </div>
				 <div class="row">
				     <div class="col-md-12">
					 <div class="form-group">
					   <label class="bmd-label-floating">Description</label>
					   <input type="text" name="slug" class="form-control">
					 </div>
				     </div>
                         </div><br><br>
				 <a href="{{ route('category.index')}}" class="btn btn-danger">Retour</a>
				<button type="submit" class="btn btn-primary">Ajouter</button>
			  
			 </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
       

@endsection


@push('script')

 

@endpush

resources/views/admin/category/edit.blade.php
@extends('layouts.app')

<!--titre du slider-->
@section('title', 'Categorie')

@push('css')


@endpush

@section('content')
    <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
		 <!--		Message flash d"erreur de validation-->
		   @include('layouts.partial.messages')
<!--	Message flash-->
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Editer la categorie</h4>
                </div>
                <div class="card-body">
                  <div class="card-content">
			 <form method="POST" action="{{ route('category.update', $category->id)}}">
			      @csrf
				@method('PUT')
				 <div class="row">
					<div class="col-md-12">
					  <div class="form-group">
					    <label class="bmd-label-floating">Nom</label>
					    <input type="text" name="name" class="form-control" value="{{ $category->name}}">
					  </div>
					</div>
				 </div>
				 <div class="row">
				     <div class="col-md-12">
					 <div class="form-group">
					   <label class="bmd-label-floating">Desc</label>
					   <input type="text" name="slug" class="form-control" value="{{ $category->slug}}">
					 </div>
				     </div>
                         </div><br><br>
				 <a href="{{ route('category.index')}}" class="btn btn-danger">Retour</a>
				<button type="submit" class="btn btn-primary">Editer</button>
			  
			 </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
       

@endsection


@push('script')

 

@endpush

resources/views/admin/category/index.blade.php
@extends('layouts.app')

<!--titre du slider-->
@section('title', 'Slider')

@push('css')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/plug-ins/3cfcc339e89/integration/bootstrap/3/dataTables.bootstrap.css">

@endpush

@section('content')
    <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
<!--		Message flash-->
            @include('layouts.partial.messages')
<!--	end	Message flash-->
<!--		 boutton d'ajout du nouveau slide-->
		  <a href="{{ route('category.create') }}" class="btn btn-info">Ajouter une categorie</a> 
<!--	end	 boutton d'ajout du nouveau slide-->		  
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Liste des categories</h4>
			
                </div>
                <div class="card-body">
                  <div class="table-responsive">
			 <table id="example" class="table" style="width:900px;">
                      <thead class=" text-primary">
				  <th>ID</th>
				  <th>Nom </th>
				  <th>Destription</th>
				  <th>Date de création</th>
				  <th>Date de modification</th>
				  <th>Actions</th>
                      </thead>
                      <tbody>
			       @foreach ($categories as $key=>$category)
				    <tr>
					  <td class="badge">{{ $key +1 }}</td>
					  <td>{{ $category->name }}</td>
					  <td>{{ $category->slug }}</td>
					  <td>{{ $category->created_at }}</td>
					  <td>{{ $category->updated_at }}</td>
					  <td>
					   <a href="{{ route('category.edit', $category->id )}}" class="btn btn-info btn-sm"><i class="material-icons">mode_edit</i></a>
					   <form id="delete-form-{{ $category->id}}" action="{{ route('category.destroy',$category->id) }}" method="POST" style="display: none;">
					     @csrf
					     @method('DELETE')
					   </form>
					   <button type="button" class="btn btn-info btn-sm"  onclick="if(confirm('Voulez-vous vraiment supprimer cette categorie ?')){
						 event.preventDefault();
						 document.getElementById('delete-form-{{ $category->id}}').submit();
						}else{
						 event.preventDefault();
						}" ><i class="material-icons">delete</i></button>
					  </td>
				    </tr>
				  @endforeach 
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
       

@endsection


@push('script')

 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
<script language="JavaScript" src="https://cdn.datatables.net/plug-ins/3cfcc339e89/integration/bootstrap/3/dataTables.bootstrap.js" type="text/javascript"></script>
 <script>
        $(document).ready(function() {
        $('#example').DataTable( {
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/French.json"
            }

        } );
         $("[data-toggle=tooltip]").tooltip();
           } );
</script>
 

@endpush