routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
 Route::get('/', 'HomeController@index')->name('welcome');
 Route::Post('/reservation', 'ReservationController@reserv')->name('reservation.reserv');
 Route::Post('/contact', 'ContactController@message')->name('contact.message');

Auth::routes();

//Route de l'administrateur
Route::group(['prefix'=>'admin', 'middleware'=>'auth', 'namespace'=>'admin'], function (){
 //    route du dashboard
    Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');
//    route des slides
    Route::resource('slider', 'SliderController');
//    route des categories
    Route::resource('category', 'CategoryController');
//    route des articles
    Route::resource('article', 'ArticleController');
 //    route des réservations
    Route::get('reservation', 'ReservationController@index')->name('reservation.index');
    
    Route::post('reservation/{id}', 'ReservationController@statut')->name('reservation.statut');

    
    Route::delete('reservation/{id}', 'ReservationController@destroy')->name('reservation.destroy');
    
    Route::get('contact', 'ContactController@index')->name('contact.index');
    
    Route::get('contact/{id}', 'ContactController@show')->name('contact.show');
    
     Route::delete('contact/{id}', 'ContactController@destroy')->name('contact.destroy');

   
});

resources/views/layouts/partial/footer.blade.php
<footer class="footer">
	    <div class="container-fluid">
		
		<div class="copyright float-right">
		  &copy;
		  {{ date('Y') }}, Binou pro <i class="material-icons">favorite</i> by bINOU aBOULAYE
           
		</div>
	    </div>
	  </footer>

resources/views/layouts/partial/messages.blade.php
@if ($errors->any())
                    <div class="alert alert-danger">
			   <ul>
			       @foreach ($errors->all() as $error)
				   <div class="alert alert-danger">
				    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<i class="material-icons">*</i>
				    </button>
				    <span>
					<b> Danger - {{ $error }}</span>
				  </div>
				 @endforeach
			   </ul>
                       
                    </div>
@endif


		  @if (session('success'))      
		     <div class="alert alert-success">
				    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<i class="material-icons">*</i>
				    </button>
				    <span>
					<b> Danger - {{ session('success') }}</span>
			</div>
                @endif

resources/views/layouts/partial/sidebar.blade.php
<div class="sidebar" data-color="purple" data-background-color="white" data-image="{{ asset('backend/img/sidebar-1.jpg ') }}">
	  <!--
	    Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

	    Tip 2: you can also add an image using data-image tag
	-->
	  <div class="logo">
	    <a href="http://www.creative-tim.com" class="simple-text logo-normal">
		Creative Tim
	    </a>
	  </div>
	  <div class="sidebar-wrapper">
	    <ul class="nav">
<!--	     Request::is('la route') ? 'active': '', active l'onglet au click-->
		<li class="{{ Request::is('admin/dashboard*') ? 'active': '' }}">
		  <a class="nav-link" href="{{ route('admin.dashboard') }}">
		    <i class="material-icons">dashboard</i>
		    <p>Dashboard</p>
		  </a>
		</li>
		<li class="{{ Request::is('admin/slider*') ? 'active': '' }}">
		  <a class="nav-link" href="{{ route('slider.index') }}">
		    <i class="material-icons">slideshow</i>
		    <p>Slide</p>
		  </a>
		</li>
		<li class="{{ Request::is('admin/category*') ? 'active': '' }}">
		  <a class="nav-link" href="{{ route('category.index') }}">
		    <i class="material-icons">content_paste</i>
		    <p>Categorie</p>
		  </a>
		</li>
		<li class="{{ Request::is('admin/article*') ? 'active': '' }}">
		  <a class="nav-link" href="{{ route('article.index') }}">
		    <i class="material-icons">library_books</i>
		    <p>Article</p>
		  </a>
		</li>
		<li class="{{ Request::is('admin/reservation*') ? 'active': '' }}">
		  <a class="nav-link" href="{{ route('reservation.index') }}">
		    <i class="material-icons">chrome_reader_mode</i>
		    <p>Reservation</p>
		  </a>
		</li>
		<li class="{{ Request::is('admin/contact*') ? 'active': '' }}">
		  <a class="nav-link" href="{{ route('contact.index') }}">
		    <i class="material-icons">forum</i>
		    <p>Message</p>
		  </a>
		</li>
		
	    </ul>
	  </div>
	</div>

resources/views/layouts/partial/topbar.blade.php
<nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="#pablo">Bienvenue {{ Auth::user()->name }}</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="material-icons">dashboard</i>
                  <p class="d-lg-none d-md-block">
                    Stats
                  </p>
                </a>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
                 <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
			  <a class="dropdown-item" href="#">Profile</a>

					    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
						  {{ Auth::user()->name }} <span class="caret"></span>
					    </a>

					    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
						  <a class="dropdown-item" href="{{ route('logout') }}"
						     onclick="event.preventDefault();
									 document.getElementById('logout-form').submit();">
							{{ __('Se déconnecter') }}
						  </a>

						  <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
							@csrf
						  </form>
					    </div>
                    </div>
                </li>
            </ul>
          </div>
        </div>
</nav>