routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
 Route::get('/', 'HomeController@index')->name('welcome');
 Route::Post('/reservation', 'ReservationController@reserv')->name('reservation.reserv');
 Route::Post('/contact', 'ContactController@message')->name('contact.message');

Auth::routes();

//Route de l'administrateur
Route::group(['prefix'=>'admin', 'middleware'=>'auth', 'namespace'=>'admin'], function (){
 //    route du dashboard
    Route::get('dashboard', 'DashboardController@index')->name('admin.dashboard');
//    route des slides
    Route::resource('slider', 'SliderController');
//    route des categories
    Route::resource('category', 'CategoryController');
//    route des articles
    Route::resource('article', 'ArticleController');
 //    route des réservations
    Route::get('reservation', 'ReservationController@index')->name('reservation.index');
    
    Route::post('reservation/{id}', 'ReservationController@statut')->name('reservation.statut');

    
    Route::delete('reservation/{id}', 'ReservationController@destroy')->name('reservation.destroy');
    
    Route::get('contact', 'ContactController@index')->name('contact.index');
    
    Route::get('contact/{id}', 'ContactController@show')->name('contact.show');
    
     Route::delete('contact/{id}', 'ContactController@destroy')->name('contact.destroy');

   
});

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{

    protected $fillable = [
        'title', 'sub_title', 'image',
    ];
}

app/Http/Controllers/Admin/SliderController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Slider;
use Carbon\Carbon;
use App\Http\Controllers\Controller;

class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $sliders = Slider::all();
        return view('admin.slider.index', compact('sliders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.slider.create');
    }

    /**
     * Création du slide.
     * Store a newly created resource in storage
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       request()->validate([
	     'title' => 'required', 
	     'sub_title' => 'required', 
	     'image' => 'required|mimes:jpeg,jpg,bmp,png', 
	 ]);
//	création de l'image
	 $image = $request->file('image');
	 $slug = str_slug($request->title);
	 if (isset($image)){
	    $currenDate = Carbon::now()->toDateString();
	    $imagename = $slug .'-'. $currenDate .'-'. uniqid() .'.'. $image->getClientOriginalExtension();
	    if (!file_exists('uploads/slider')){
	     mkdir('uploads/slider', 0777, true);
	    }
	    $image->move('uploads/slider', $imagename);
	 }
	else {
        $imagename = 'default.png';
      }
	//	fin création de l'image
	$slider = new Slider();
	$slider->title = $request->title;
	$slider->sub_title = $request->sub_title;
	$slider->image = $imagename;
      
     $slider->save();
	
	
	return redirect()->route('slider.index')->with('success', 'Slide ajouté avec succès !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $slider = Slider::find($id);
	  return view('admin.slider.edit', compact('slider'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       request()->validate([
	     'title' => 'required', 
	     'sub_title' => 'required', 
	     'image' => 'mimes:jpeg,jpg,bmp,png', 
	 ]);
	 $image = $request->file('image');
	 $slug = str_slug($request->title);
	 $slider = Slider::find($id);
	 if (isset($image)){
	    $currenDate = Carbon::now()->toDateString();
	    $imagename = $slug .'-'. $currenDate .'-'. uniqid() .'.'. $image->getClientOriginalExtension();
	    if (!file_exists('uploads/slider')){
	     mkdir('uploads/slider', 0777, true);
	    }
	    $image->move('uploads/slider', $imagename);
	 }
	else {
        $imagename = $slider->image;
      }
	
             $slider->title = $request->title;
             $slider->sub_title = $request->sub_title;
             $slider->image = $imagename;  
             $slider->save();
	return redirect()->route('slider.index')->with('success', 'Slide modifié avec succès !');
    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       $slider = Slider::find($id);
	 if (file_exists('uploads/slider/'.$slider->image))
	 {
	    unlink('uploads/slider/'.$slider->image);
	   
	 }
	  $slider->delete();  
	  return redirect()->back()->with('success', 'Slide supprimé avec succès !');
    }
}

resources/views/admin/slider/create.blade.php
@extends('layouts.app')

<!--titre du slider-->
@section('title', 'Slider')

@push('css')


@endpush

@section('content')
    <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
		 <!--		Message flash d"erreur de validation-->
		  
		   @if ($errors->any())
                    <div class="alert alert-danger">
			   <ul>
			       @foreach ($errors->all() as $error)
				   <div class="alert alert-danger">
				    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<i class="material-icons">*</i>
				    </button>
				    <span>
					<b> Danger - {{ $error }}</span>
				  </div>
				 @endforeach
			   </ul>
                       
                    </div>
                @endif
		  
<!--	Message flash-->
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Ajouter un nouveau slide</h4>
                </div>
                <div class="card-body">
                  <div class="card-content">
			 <form method="POST" action="{{ route('slider.store')}}" enctype="multipart/form-data">
			      @csrf
				 <div class="row">
					<div class="col-md-12">
					  <div class="form-group">
					    <label class="bmd-label-floating">Titre</label>
					    <input type="text" name="title" class="form-control">
					  </div>
					</div>
				 </div>
				 <div class="row">
				     <div class="col-md-12">
					 <div class="form-group">
					   <label class="bmd-label-floating">Sub titre</label>
					   <input type="text" name="sub_title" class="form-control">
					 </div>
				     </div>
                         </div>
				 <div class="row">
				     <div class="col-md-12">
					 
					   <label class="control-label">Image du slide</label>
					   <input type="file" name="image" class="form-control">
					 
				     </div>
                         </div><br><br>
				 <a href="{{ route('slider.index')}}" class="btn btn-danger">Retour</a>
				<button type="submit" class="btn btn-primary">Ajouter le slide</button>
			  
			 </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
       

@endsection


@push('script')

 

@endpush

resources/views/admin/slider/edit.blade.php
@extends('layouts.app')

<!--titre du slider-->
@section('title', 'Slider')

@push('css')


@endpush

@section('content')
    <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
		 <!--		Message flash d"erreur de validation-->
		   @include('layouts.partial.messages')
<!--	Message flash-->
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Editer le slide</h4>
                </div>
                <div class="card-body">
                  <div class="card-content">
			 <form method="POST" action="{{ route('slider.update', $slider->id)}}" enctype="multipart/form-data">
			      @csrf
				@method('PUT')
				 <div class="row">
					<div class="col-md-12">
					  <div class="form-group">
					    <label class="bmd-label-floating">Titre</label>
					    <input type="text" name="title" class="form-control" value="{{ $slider->title}}">
					  </div>
					</div>
				 </div>
				 <div class="row">
				     <div class="col-md-12">
					 <div class="form-group">
					   <label class="bmd-label-floating">Sub titre</label>
					   <input type="text" name="sub_title" class="form-control" value="{{ $slider->sub_title}}">
					 </div>
				     </div>
                         </div>
				 <div class="row">
				     <div class="col-md-12">
					 
					   <label class="control-label">Image du slide</label>
					   <input type="file" name="image" class="form-control">
					 
				     </div>
                         </div><br><br>
				 <a href="{{ route('slider.index')}}" class="btn btn-danger">Retour</a>
				<button type="submit" class="btn btn-primary">Editer</button>
			  
			 </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
       

@endsection


@push('script')

 

@endpush

resources/views/admin/slider/index.blade.php
@extends('layouts.app')

<!--titre du slider-->
@section('title', 'Slider')

@push('css')
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<link rel="stylesheet" type="text/css" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="http://cdn.datatables.net/plug-ins/3cfcc339e89/integration/bootstrap/3/dataTables.bootstrap.css">

@endpush

@section('content')
    <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
<!--		Message flash-->
            @include('layouts.partial.messages')
<!--	end	Message flash-->
<!--		 boutton d'ajout du nouveau slide-->
		  <a href="{{ route('slider.create') }}" class="btn btn-info">Ajouter un slide</a> 
<!--	end	 boutton d'ajout du nouveau slide-->		  
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Liste des slides</h4>
			
                </div>
                <div class="card-body">
                  <div class="table-responsive">
			 <table id="example" class="table" style="width:900px;">
                      <thead class=" text-primary">
				  <th>ID</th>
				  <th>Titre </th>
				  <th>Sub titre</th>
				  <th>Image</th>
				  <th>Date de création</th>
				  <th>Date de modification</th>
				  <th>Actions</th>
                      </thead>
                      <tbody>
			       @foreach ($sliders as $key=>$slider)
				    <tr>
					  <td class="badge">{{ $key +1 }}</td>
					  <td>{{ $slider->title }}</td>
					  <td>{{ $slider->sub_title }}</td>
					  <td>{{ $slider->image }}</td>
					  <td>{{ $slider->created_at }}</td>
					  <td>{{ $slider->updated_at }}</td>
					  <td>
					   <a href="{{ route('slider.edit', $slider->id )}}" class="btn btn-info btn-sm">Editer</a>
					   <form id="delete-form-{{ $slider->id}}" action="{{ route('slider.destroy',$slider->id) }}" method="POST" style="display: none;">
					     @csrf
					     @method('DELETE')
					   </form>
					   <button type="button" class="btn btn-info btn-sm"  onclick="if(confirm('Voulez-vous vraiment supprimer ce slide ?')){
						 event.preventDefault();
						 document.getElementById('delete-form-{{ $slider->id}}').submit();
						}else{
						 event.preventDefault();
						}" >Supprimer</button>
					  </td>
				    </tr>
				  @endforeach 
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
       

@endsection


@push('script')

 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js"></script>
<script language="JavaScript" src="https://cdn.datatables.net/plug-ins/3cfcc339e89/integration/bootstrap/3/dataTables.bootstrap.js" type="text/javascript"></script>
 <script>
        $(document).ready(function() {
        $('#example').DataTable( {
            "language": {
                "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/French.json"
            }

        } );
         $("[data-toggle=tooltip]").tooltip();
           } );
</script>
 

@endpush